'use client';

/**
 * The drafting stage: sections generated by server jobs, not by this component.
 *
 * The old `long-form-view` drove generation from a `while (true)` loop inside a
 * React component. That is why closing a tab used to throw away a section that
 * had already been generated and billed, and why a refresh had to coerce
 * `writing` back to `paused` — the loop was the only thing that knew work was in
 * flight, so if it died the state was a lie.
 *
 * Neither of those survives the port. Generation lives in `jobs`, this component
 * holds no generation state at all, and the two things that used to be local
 * truth are now read from the server: whether work is outstanding comes from the
 * job rows, and what has been written comes from `artifact.long_form`. There is
 * consequently no "coerce to paused on mount" effect, because there is nothing
 * for it to correct — a job may well still be running, and the UI must not claim
 * otherwise.
 *
 * `useJobDrain` is a latency optimisation and nothing more. Cron finishes the
 * document whether or not this component is ever mounted.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { useJobDrain } from '@/hooks/use-job-drain';
import { classifyDrainError, classified, withPreserved, type ErrorCode } from '@/lib/jobs/errors';
import {
  enqueueSectionJob,
  listProjectJobs,
  requestProjectCancel,
  type ProjectJob,
} from '@/lib/supabase/jobs';
import type { OutlineSection } from '@/types';
import type { StageRendererProps } from './types';

/** Statuses that mean the server still has work to do. */
const PENDING_STATUSES = new Set(['queued', 'leased']);

export function LongFormRenderer(props: StageRendererProps) {
  const { longForm: ctx, readOnly } = props;

  if (!ctx) {
    return (
      <Panel>
        <p className="text-body text-[var(--on-surface)]">
          This stage is not wired to a project yet.
        </p>
      </Panel>
    );
  }

  return <Drafting ctx={ctx} readOnly={readOnly} />;
}

interface DraftingProps {
  ctx: NonNullable<StageRendererProps['longForm']>;
  readOnly: boolean;
}

function Drafting({ ctx, readOnly }: DraftingProps) {
  const { project, artifactId, state, approvedOutlineVersionId, stageId, onRefresh } = ctx;

  const [jobs, setJobs] = useState<ProjectJob[]>([]);
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());

  const outline = useMemo<OutlineSection[]>(() => state?.outline ?? [], [state]);
  const complete = outline.filter((s) => s.status === 'complete').length;

  const pendingJobs = useMemo(
    () => jobs.filter((j) => PENDING_STATUSES.has(j.status)),
    [jobs]
  );

  const refreshJobs = useCallback(async () => {
    try {
      setJobs(await listProjectJobs(project.id));
    } catch {
      // A failed status poll is not worth showing: the section list below is
      // still accurate, because it comes from the artifact rather than the queue.
    }
  }, [project.id]);

  // Poll rather than subscribe. Realtime is not used anywhere else in the app,
  // and the drain hook is already on a 1-3s loop, so a poll on the same order
  // costs one query and introduces no new infrastructure.
  const pollRef = useRef(refreshJobs);
  useEffect(() => {
    pollRef.current = refreshJobs;
  }, [refreshJobs]);
  useEffect(() => {
    void pollRef.current();
    const timer = setInterval(() => void pollRef.current(), 3_000);
    return () => clearInterval(timer);
  }, [project.id]);

  const handleProgress = useCallback(() => {
    void refreshJobs();
    onRefresh();
  }, [refreshJobs, onRefresh]);

  useJobDrain({
    projectId: project.id,
    hasPendingJobs: pendingJobs.length > 0,
    onProgress: handleProgress,
  });

  const run = useCallback(
    async (action: () => Promise<void>) => {
      setBusy(true);
      setActionError(null);
      try {
        await action();
        await refreshJobs();
        onRefresh();
      } catch (error) {
        setActionError(withPreserved(classifyDrainError(error), complete, outline.length).message);
      } finally {
        setBusy(false);
      }
    },
    [refreshJobs, onRefresh, complete, outline.length]
  );

  const startDrafting = () =>
    run(async () => {
      if (!artifactId) throw new Error('This stage has no artifact to draft into.');
      // Enqueue every section that is not already written. Sections that are
      // done collide on their idempotency key and quietly do nothing, which is
      // the "not regenerated unless requested" guarantee doing its job.
      for (const [index, section] of outline.entries()) {
        if (section.status === 'complete') continue;
        await enqueueSectionJob({
          project,
          artifactId,
          stageId,
          outlineVersionId: approvedOutlineVersionId,
          sectionId: section.id,
          sectionIndex: index,
          revision: section.revision ?? 0,
        });
      }
    });

  const pause = () => run(async () => void (await requestProjectCancel(project.id)));

  const regenerate = (section: OutlineSection, index: number) =>
    run(async () => {
      if (!artifactId) throw new Error('This stage has no artifact to draft into.');
      // A new revision means a new idempotency key, which is what makes this an
      // explicit user request rather than a no-op.
      await enqueueSectionJob({
        project,
        artifactId,
        stageId,
        outlineVersionId: approvedOutlineVersionId,
        sectionId: section.id,
        sectionIndex: index,
        revision: (section.revision ?? 0) + 1,
      });
    });

  const toggle = (id: string) =>
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  if (!outline.length) {
    return (
      <Panel>
        <p className="text-body text-[var(--on-surface)]">
          There is no approved outline to draft from yet.
        </p>
        <p className="mt-1 text-label text-[var(--on-surface-variant)]">
          Approve an outline in the outline stage and drafting will follow it.
        </p>
      </Panel>
    );
  }

  const jobBySection = new Map(
    jobs
      .filter((j) => typeof j.payload?.section_id === 'string')
      .map((j) => [j.payload!.section_id as string, j] as const)
  );

  const running = pendingJobs.length > 0;
  const failures = jobs.filter((j) => j.status === 'failed' || j.status === 'dead');

  return (
    <div className="space-y-6">
      <Panel>
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-label text-[var(--on-surface-variant)]">Drafting</p>
            <p className="mt-1 text-body text-[var(--on-surface)]">
              {complete} of {outline.length} sections written
              {running ? ` · ${pendingJobs.length} queued` : ''}
            </p>
            {!approvedOutlineVersionId && (
              <p className="mt-1 text-label text-[var(--on-surface-variant)]">
                No approved outline version — sections will not record what they were written
                against.
              </p>
            )}
          </div>

          {!readOnly && (
            <div className="flex items-center gap-3">
              {running ? (
                <button
                  type="button"
                  onClick={pause}
                  disabled={busy}
                  className="rounded-lg bg-[var(--surface-container-high)] px-4 py-2 text-label font-semibold text-[var(--on-surface)] disabled:opacity-50"
                >
                  Pause
                </button>
              ) : (
                <button
                  type="button"
                  onClick={startDrafting}
                  disabled={busy || complete === outline.length}
                  className="rounded-lg bg-[var(--pm-primary)] px-4 py-2 text-label font-semibold text-white disabled:opacity-50"
                >
                  {complete === 0 ? 'Start drafting' : 'Resume drafting'}
                </button>
              )}
            </div>
          )}
        </div>

        {/* Progress is read from the artifact, so it is correct even if this tab
            has been closed since the sections were written. */}
        <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-[var(--surface-container-high)]">
          <div
            className="h-full rounded-full bg-[var(--pm-primary)] transition-all"
            style={{ width: `${(complete / outline.length) * 100}%` }}
          />
        </div>
      </Panel>

      {actionError && <Notice tone="error">{actionError}</Notice>}

      {failures.map((job) => (
        <Notice key={job.id} tone="error">
          <span className="font-semibold">
            {classified((job.error_code as ErrorCode) ?? 'unknown').title}.
          </span>{' '}
          {job.error_message ??
            withPreserved(classified('unknown'), complete, outline.length).message}
        </Notice>
      ))}

      <Panel>
        <h3 className="text-label font-semibold text-[var(--on-surface)]">Sections</h3>
        <ol className="mt-4 space-y-3">
          {outline.map((section, index) => (
            <SectionRow
              key={section.id}
              section={section}
              index={index}
              job={jobBySection.get(section.id) ?? null}
              expanded={expanded.has(section.id)}
              onToggle={() => toggle(section.id)}
              onRegenerate={readOnly ? undefined : () => regenerate(section, index)}
              busy={busy}
            />
          ))}
        </ol>
      </Panel>
    </div>
  );
}

interface SectionRowProps {
  section: OutlineSection;
  index: number;
  job: ProjectJob | null;
  expanded: boolean;
  onToggle: () => void;
  onRegenerate?: () => void;
  busy: boolean;
}

function SectionRow({
  section,
  index,
  job,
  expanded,
  onToggle,
  onRegenerate,
  busy,
}: SectionRowProps) {
  // The job row is the authority on "in flight"; the artifact is the authority
  // on "written". Neither is inferred from the other.
  const inFlight = job !== null && PENDING_STATUSES.has(job.status);
  const done = section.status === 'complete';

  return (
    <li className="rounded-lg bg-[var(--surface-container-low)] px-4 py-3">
      <div className="flex items-start gap-3">
        <StatusIcon done={done} inFlight={inFlight} failed={job?.status === 'dead' || job?.status === 'failed'} />

        <div className="min-w-0 flex-1">
          <div className="flex items-start justify-between gap-4">
            <button
              type="button"
              onClick={onToggle}
              disabled={!section.content}
              className="text-left text-body font-semibold text-[var(--on-surface)] disabled:cursor-default"
            >
              {index + 1}. {section.title}
            </button>

            {done && onRegenerate && (
              <button
                type="button"
                onClick={onRegenerate}
                disabled={busy || inFlight}
                className="shrink-0 text-label font-semibold text-[var(--pm-primary)] disabled:opacity-50"
              >
                Regenerate
              </button>
            )}
          </div>

          <p className="mt-1 text-label text-[var(--on-surface-variant)]">{section.abstract}</p>

          {inFlight && (
            <p className="mt-2 text-label text-[var(--on-surface-variant)]">
              {job?.status === 'leased' ? 'Writing…' : 'Queued'}
              {job && job.attempts > 1 ? ` · attempt ${job.attempts} of ${job.max_attempts}` : ''}
            </p>
          )}

          {section.finish_reason === 'length' && done && (
            <p className="mt-2 text-label text-[var(--on-surface-variant)]">
              This section reached the model&apos;s output limit and may stop mid-thought.
              Regenerating usually completes it.
            </p>
          )}

          {expanded && section.content && (
            <div className="mt-3 whitespace-pre-wrap text-body leading-relaxed text-[var(--on-surface)]">
              {section.content}
            </div>
          )}
        </div>
      </div>
    </li>
  );
}

function StatusIcon({
  done,
  inFlight,
  failed,
}: {
  done: boolean;
  inFlight: boolean;
  failed: boolean;
}) {
  if (done) {
    return (
      <span className="material-symbols-outlined text-[var(--pm-primary)]" aria-hidden>
        check_circle
      </span>
    );
  }
  if (failed) {
    return (
      <span className="material-symbols-outlined text-[var(--on-surface-variant)]" aria-hidden>
        error
      </span>
    );
  }
  if (inFlight) {
    return (
      <span className="material-symbols-outlined animate-pulse text-[var(--on-surface)]" aria-hidden>
        edit
      </span>
    );
  }
  return (
    <span className="material-symbols-outlined text-[var(--on-surface-variant)]" aria-hidden>
      radio_button_unchecked
    </span>
  );
}

function Panel({ children }: { children: React.ReactNode }) {
  return <div className="rounded-xl bg-[var(--surface-container)] p-6">{children}</div>;
}

function Notice({ tone, children }: { tone: 'error'; children: React.ReactNode }) {
  return (
    <div
      role={tone === 'error' ? 'alert' : undefined}
      className="rounded-lg bg-[var(--surface-container-high)] px-4 py-3 text-label text-[var(--on-surface)]"
    >
      {children}
    </div>
  );
}
