'use client';

/**
 * The drafting stage: sections generated by server jobs, not by this component.
 *
 * The old `long-form-view` drove generation from a `while (true)` loop inside a
 * React component. That is why closing a tab used to throw away a section that
 * had already been generated and billed, and why a refresh had to coerce
 * `writing` back to `paused` — the loop was the only thing that knew work was in
 * flight, so if it died the state was a lie.
 *
 * Neither of those survives the port. Generation lives in `jobs`, this component
 * holds no generation state at all, and the two things that used to be local
 * truth are now read from the server: whether work is outstanding comes from the
 * job rows, and what has been written comes from `artifact.long_form`. There is
 * consequently no "coerce to paused on mount" effect, because there is nothing
 * for it to correct — a job may well still be running, and the UI must not claim
 * otherwise.
 *
 * `useJobDrain` is a latency optimisation and nothing more. Cron finishes the
 * document whether or not this component is ever mounted.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from 'react';

import { useJobDrain } from '@/hooks/use-job-drain';
import { classifyDrainError, classified, withPreserved, type ErrorCode } from '@/lib/jobs/errors';
import {
  enqueueSectionJob,
  isStoppedJob,
  listProjectJobs,
  requestProjectCancel,
  revisionToEnqueue,
  type ProjectJob,
} from '@/lib/supabase/jobs';
import { appendVersion } from '@/lib/supabase/versions';
import { formatManuscript } from '@/lib/workflow/digest';
import { formatRevisionNotes } from '@/lib/workflow/revision';
import type { OutlineSection } from '@/types';
import type { Artifact } from '@/types/project';
import type { StageRendererProps } from './types';
import { LargeJobWarning, isLargeJob } from '@/components/workflow/large-job-warning';
import { useReportPanelStep } from '@/components/workflow/use-report-panel-step';

/** Statuses that mean the server still has work to do. */
const PENDING_STATUSES = new Set(['queued', 'leased']);

export function LongFormRenderer(props: StageRendererProps) {
  const { longForm: ctx, readOnly } = props;

  if (!ctx) {
    return (
      <Panel>
        <p className="text-body text-[var(--on-surface)]">
          This stage is not wired to a project yet.
        </p>
      </Panel>
    );
  }

  return <Drafting ctx={ctx} readOnly={readOnly} />;
}

interface DraftingProps {
  ctx: NonNullable<StageRendererProps['longForm']>;
  readOnly: boolean;
}

function Drafting({ ctx, readOnly }: DraftingProps) {
  const { project, artifactId, state, approvedOutlineVersionId, stageId, onRefresh, appendManuscriptVersion } = ctx;
  const revise = ctx.revise ?? null;

  const [jobs, setJobs] = useState<ProjectJob[]>([]);
  const [busy, setBusy] = useState(false);
  const [actionError, setActionError] = useState<string | null>(null);
  const [expanded, setExpanded] = useState<Set<string>>(new Set());
  // FR-18: gate a large drafting run behind an explicit confirmation.
  const [confirmingLargeJob, setConfirmingLargeJob] = useState(false);

  const outline = useMemo<OutlineSection[]>(() => state?.outline ?? [], [state]);
  const complete = outline.filter((s) => s.status === 'complete').length;

  const pendingJobs = useMemo(
    () => jobs.filter((j) => PENDING_STATUSES.has(j.status)),
    [jobs]
  );

  // Jobs arrive oldest first, so the map ends up holding each section's latest.
  const jobBySection = useMemo(
    () =>
      new Map(
        jobs
          .filter((j) => typeof j.payload?.section_id === 'string')
          .map((j) => [j.payload!.section_id as string, j] as const)
      ),
    [jobs]
  );

  const refreshJobs = useCallback(async () => {
    try {
      setJobs(await listProjectJobs(project.id));
    } catch {
      // A failed status poll is not worth showing: the section list below is
      // still accurate, because it comes from the artifact rather than the queue.
    }
  }, [project.id]);

  // Poll rather than subscribe. Realtime is not used anywhere else in the app,
  // and the drain hook is already on a 1-3s loop, so a poll on the same order
  // costs one query and introduces no new infrastructure.
  const pollRef = useRef(refreshJobs);
  useEffect(() => {
    pollRef.current = refreshJobs;
  }, [refreshJobs]);
  useEffect(() => {
    void pollRef.current();
    const timer = setInterval(() => void pollRef.current(), 3_000);
    return () => clearInterval(timer);
  }, [project.id]);

  const handleProgress = useCallback(() => {
    void refreshJobs();
    onRefresh();
  }, [refreshJobs, onRefresh]);

  useJobDrain({
    projectId: project.id,
    hasPendingJobs: pendingJobs.length > 0,
    onProgress: handleProgress,
  });

  const run = useCallback(
    async (action: () => Promise<void>) => {
      setBusy(true);
      setActionError(null);
      try {
        await action();
        await refreshJobs();
        onRefresh();
      } catch (error) {
        setActionError(withPreserved(classifyDrainError(error), complete, outline.length).message);
      } finally {
        setBusy(false);
      }
    },
    [refreshJobs, onRefresh, complete, outline.length]
  );

  /**
   * FR-18: ask before committing to a large run.
   *
   * Counted over the sections that will *actually* be drafted — completed ones
   * collide on their idempotency key and cost nothing, so including them would
   * warn about spending that is not going to happen.
   */
  const pendingSectionCount = outline.filter((s) => s.status !== 'complete').length;

  const requestDrafting = () => {
    if (isLargeJob(pendingSectionCount)) {
      setConfirmingLargeJob(true);
      return;
    }
    void startDrafting();
  };

  const startDrafting = () =>
    run(async () => {
      setConfirmingLargeJob(false);
      if (!artifactId) throw new Error('This stage has no artifact to draft into.');
      // Enqueue every section that is not already written. Sections that are
      // done collide on their idempotency key and quietly do nothing, which is
      // the "not regenerated unless requested" guarantee doing its job.
      for (const [index, section] of outline.entries()) {
        if (section.status === 'complete') continue;
        await enqueueSectionJob({
          project,
          artifactId,
          stageId,
          outlineVersionId: approvedOutlineVersionId,
          sectionId: section.id,
          sectionIndex: index,
          // A section whose last job gave up needs a fresh key, or resuming
          // collides with the dead row and does nothing (PM-04).
          revision: revisionToEnqueue(section, jobBySection.get(section.id) ?? null),
        });
      }
    });

  const pause = () => run(async () => void (await requestProjectCancel(project.id)));

  const regenerate = (section: OutlineSection, index: number) =>
    run(async () => {
      if (!artifactId) throw new Error('This stage has no artifact to draft into.');
      // A new revision means a new idempotency key, which is what makes this an
      // explicit user request rather than a no-op.
      await enqueueSectionJob({
        project,
        artifactId,
        stageId,
        outlineVersionId: approvedOutlineVersionId,
        sectionId: section.id,
        sectionIndex: index,
        revision: (section.revision ?? 0) + 1,
      });
    });

  /** Try a section again after it gave up (PM-04). The failure notice used to say to, with no way to. */
  const retry = (section: OutlineSection, index: number) =>
    run(async () => {
      if (!artifactId) throw new Error('This stage has no artifact to draft into.');
      await enqueueSectionJob({
        project,
        artifactId,
        stageId,
        outlineVersionId: approvedOutlineVersionId,
        sectionId: section.id,
        sectionIndex: index,
        revision: revisionToEnqueue(section, jobBySection.get(section.id) ?? null),
      });
    });

  /**
   * Revision and Editing: rewrite the written sections with the stage's brief
   * and the findings accepted before it. The manuscript as it stood is saved
   * as a version first, because a rewrite replaces each section's text in
   * place and "each accepted finding becomes a version you can compare
   * against" is what the stage promises.
   */
  const reviseSections = (targets: { section: OutlineSection; index: number }[]) =>
    run(async () => {
      if (!artifactId || !revise) throw new Error('This stage has no manuscript to revise.');
      const snapshot = {
        content: formatManuscript(outline, Number.POSITIVE_INFINITY),
        source_operation: 'manuscript_snapshot',
        instruction: `Before ${revise.stageLabel}`,
        model: '',
        mode: project.mode,
        change_summary: `The manuscript as it stood before ${revise.stageLabel}.`,
      };
      // Through the store when the workspace provides it, so the snapshot is
      // in the bundle at once; the raw write is only for a caller without one.
      if (appendManuscriptVersion) await appendManuscriptVersion(snapshot);
      else await appendVersion({ id: artifactId, user_id: project.user_id, project_id: project.id } as Artifact, snapshot);
      const brief = {
        stage_label: revise.stageLabel,
        instruction: revise.instruction,
        notes: formatRevisionNotes(revise.findings),
      };
      for (const { section, index } of targets) {
        await enqueueSectionJob({
          project,
          artifactId,
          stageId,
          outlineVersionId: approvedOutlineVersionId,
          sectionId: section.id,
          sectionIndex: index,
          revision: (section.revision ?? 0) + 1,
          revise: brief,
        });
      }
    });

  // A section counts as revised here once any job this stage queued for it
  // succeeded — not only its latest job, which after Editing runs is Editing's,
  // and would make Revision read as never applied.
  const revisedCount = revise
    ? outline.filter((s) =>
        jobs.some(
          (j) =>
            j.status === 'succeeded' &&
            j.payload?.stage_id === stageId &&
            j.payload?.section_id === s.id
        )
      ).length
    : 0;

  const reviseAll = () =>
    void reviseSections(
      outline.flatMap((section, index) => (section.status === 'complete' ? [{ section, index }] : []))
    );
  const findingCount = revise?.findings.length ?? 0;
  const reviseLabel =
    findingCount > 0
      ? `Apply ${findingCount} finding${findingCount === 1 ? '' : 's'} to every section`
      : `Run ${(revise?.stageLabel ?? '').toLowerCase()} on every section`;

  // PM-06: the stage bar's one primary button takes this panel's step.
  useReportPanelStep(
    ctx.onPanelStep,
    stageId,
    readOnly || !outline.length
      ? null
      : pendingJobs.length > 0 || busy
        ? { label: '', reason: '', busy: true }
        : revise
          ? complete > 0 && revisedCount === 0
            ? {
                label: reviseLabel,
                reason: 'Rewrites each chapter as it stands. The current manuscript is saved as a version first.',
                run: reviseAll,
              }
            : null
          : complete < outline.length
            ? {
                label: complete === 0 ? 'Start drafting' : 'Resume drafting',
                reason: 'Writes each section against the approved outline. You can pause at any time.',
                run: requestDrafting,
              }
            : null
  );

  const toggle = (id: string) =>
    setExpanded((prev) => {
      const next = new Set(prev);
      if (next.has(id)) next.delete(id);
      else next.add(id);
      return next;
    });

  if (!outline.length) {
    return (
      <Panel>
        <p className="text-body text-[var(--on-surface)]">
          There is no approved outline to draft from yet.
        </p>
        <p className="mt-1 text-label text-[var(--on-surface-variant)]">
          {ctx.emptyHint ?? 'Approve an outline and drafting will follow it.'}
        </p>
      </Panel>
    );
  }

  const running = pendingJobs.length > 0;
  // Only a section's latest job speaks for it, and only while it is unwritten:
  // listing every failure ever recorded kept "gave up" on screen after the
  // section had been retried and written.
  const failures = outline.flatMap((section, index) => {
    const job = jobBySection.get(section.id) ?? null;
    return job && isStoppedJob(job) && job.status !== 'cancelled' && section.status !== 'complete'
      ? [{ job, section, index }]
      : [];
  });

  return (
    <div className="space-y-6">
      {revise ? (
        <RevisionPanel
          revise={revise}
          written={complete}
          total={outline.length}
          revised={revisedCount}
          running={running}
          busy={busy}
          readOnly={readOnly}
          onReviseAll={reviseAll}
          onPause={pause}
        />
      ) : (
      <Panel>
        <div className="flex flex-wrap items-center justify-between gap-4">
          <div>
            <p className="text-label text-[var(--on-surface-variant)]">Drafting</p>
            <p className="mt-1 text-body text-[var(--on-surface)]">
              {complete} of {outline.length} sections written
              {running ? ` · ${pendingJobs.length} queued` : ''}
            </p>
            {!approvedOutlineVersionId && (
              <p className="mt-1 text-label text-[var(--on-surface-variant)]">
                No approved outline version — sections will not record what they were written
                against.
              </p>
            )}
          </div>

          {!readOnly && (
            <div className="flex items-center gap-3">
              {running ? (
                <button
                  type="button"
                  onClick={pause}
                  disabled={busy}
                  className="rounded-lg bg-[var(--surface-container-high)] px-4 py-2 text-label font-semibold text-[var(--on-surface)] disabled:opacity-50"
                >
                  Pause
                </button>
              ) : complete === outline.length ? (
                // Nothing left to draft. A disabled "Resume drafting" read as a
                // next step that could not be taken.
                <span className="text-label text-[var(--on-surface-variant)]">
                  Every section is written
                </span>
              ) : (
                <button
                  type="button"
                  onClick={requestDrafting}
                  disabled={busy}
                  className="rounded-lg bg-[var(--pm-primary)] px-4 py-2 text-label font-semibold text-[var(--on-primary)] disabled:opacity-50"
                >
                  {complete === 0 ? 'Start drafting' : 'Resume drafting'}
                </button>
              )}
            </div>
          )}
        </div>

        {/* Progress is read from the artifact, so it is correct even if this tab
            has been closed since the sections were written. */}
        <div className="mt-4 h-1.5 w-full overflow-hidden rounded-full bg-[var(--surface-container-high)]">
          <div
            className="h-full rounded-full bg-[var(--pm-primary)] transition-all"
            style={{ width: `${(complete / outline.length) * 100}%` }}
          />
        </div>
      </Panel>
      )}

      {confirmingLargeJob && (
        <LargeJobWarning
          sectionCount={pendingSectionCount}
          model={project.model}
          onConfirm={() => void startDrafting()}
          onCancel={() => setConfirmingLargeJob(false)}
        />
      )}

      {actionError && <Notice tone="error">{actionError}</Notice>}

      {failures.map(({ job, section, index }) => (
        <Notice key={job.id} tone="error">
          <span className="font-semibold">
            Section {index + 1}, “{section.title}”:{' '}
            {classified((job.error_code as ErrorCode) ?? 'unknown').title}.
          </span>{' '}
          {/* Counted now, not when the job failed: the stored message said "1
              of 3 saved" after later sections had been written. */}
          {job.error_code && job.error_code !== 'unknown'
            ? withPreserved(classified(job.error_code as ErrorCode), complete, outline.length).message
            : (job.error_message ?? withPreserved(classified('unknown'), complete, outline.length).message)}
        </Notice>
      ))}

      <Panel>
        <h3 className="text-label font-semibold text-[var(--on-surface)]">Sections</h3>
        <ol className="mt-4 space-y-3">
          {outline.map((section, index) => (
            <SectionRow
              key={section.id}
              section={section}
              index={index}
              job={jobBySection.get(section.id) ?? null}
              expanded={expanded.has(section.id)}
              onToggle={() => toggle(section.id)}
              onRegenerate={
                readOnly
                  ? undefined
                  : revise
                    ? () => void reviseSections([{ section, index }])
                    : () => regenerate(section, index)
              }
              regenerateLabel={revise ? 'Revise' : 'Regenerate'}
              onRetry={readOnly ? undefined : () => retry(section, index)}
              busy={busy}
            />
          ))}
        </ol>
      </Panel>
    </div>
  );
}

interface SectionRowProps {
  section: OutlineSection;
  index: number;
  job: ProjectJob | null;
  expanded: boolean;
  onToggle: () => void;
  onRegenerate?: () => void;
  regenerateLabel?: string;
  onRetry?: () => void;
  busy: boolean;
}

function SectionRow({
  section,
  index,
  job,
  expanded,
  onToggle,
  onRegenerate,
  regenerateLabel = 'Regenerate',
  onRetry,
  busy,
}: SectionRowProps) {
  // The job row is the authority on "in flight"; the artifact is the authority
  // on "written". Neither is inferred from the other.
  const inFlight = job !== null && PENDING_STATUSES.has(job.status);
  const done = section.status === 'complete';
  const gaveUp = !done && (job?.status === 'dead' || job?.status === 'failed');

  return (
    <li className="rounded-lg bg-[var(--surface-container-low)] px-4 py-3">
      <div className="flex items-start gap-3">
        <StatusIcon done={done} inFlight={inFlight} failed={gaveUp} />

        <div className="min-w-0 flex-1">
          <div className="flex items-start justify-between gap-4">
            <button
              type="button"
              onClick={onToggle}
              disabled={!section.content}
              className="text-left text-body font-semibold text-[var(--on-surface)] disabled:cursor-default"
            >
              {index + 1}. {section.title}
            </button>

            {gaveUp && onRetry && (
              <button
                type="button"
                onClick={onRetry}
                disabled={busy}
                className="shrink-0 rounded-lg bg-[var(--pm-primary)] px-3 py-1.5 text-label font-semibold text-[var(--on-primary)] disabled:opacity-50"
              >
                Retry section
              </button>
            )}

            {done && onRegenerate && (
              <button
                type="button"
                onClick={onRegenerate}
                disabled={busy || inFlight}
                className="shrink-0 text-label font-semibold text-[var(--pm-primary)] disabled:opacity-50"
              >
                {regenerateLabel}
              </button>
            )}
          </div>

          <p className="mt-1 text-label text-[var(--on-surface-variant)]">{section.abstract}</p>
          {done && section.content && (
            <p className="mt-1 text-label text-[var(--on-surface-variant)]">
              {wordCount(section.content).toLocaleString()} words
            </p>
          )}

          {inFlight && (
            <p className="mt-2 text-label text-[var(--on-surface-variant)]">
              {job?.status === 'leased' ? 'Writing…' : 'Queued'}
              {job && job.attempts > 1 ? ` · attempt ${job.attempts} of ${job.max_attempts}` : ''}
            </p>
          )}

          {section.finish_reason === 'length' && done && (
            <p className="mt-2 text-label text-[var(--on-surface-variant)]">
              This section reached the model&apos;s output limit and may stop mid-thought.
              Regenerating usually completes it.
            </p>
          )}

          {expanded && section.content && (
            <div className="mt-3 whitespace-pre-wrap text-body leading-relaxed text-[var(--on-surface)]">
              {section.content}
            </div>
          )}
        </div>
      </div>
    </li>
  );
}

function StatusIcon({
  done,
  inFlight,
  failed,
}: {
  done: boolean;
  inFlight: boolean;
  failed: boolean;
}) {
  if (done) {
    return (
      <span className="material-symbols-outlined text-[var(--pm-primary)]" aria-hidden>
        check_circle
      </span>
    );
  }
  if (failed) {
    return (
      <span className="material-symbols-outlined text-[var(--on-surface-variant)]" aria-hidden>
        error
      </span>
    );
  }
  if (inFlight) {
    return (
      <span className="material-symbols-outlined animate-pulse text-[var(--on-surface)]" aria-hidden>
        edit
      </span>
    );
  }
  return (
    <span className="material-symbols-outlined text-[var(--on-surface-variant)]" aria-hidden>
      radio_button_unchecked
    </span>
  );
}

function Panel({ children }: { children: React.ReactNode }) {
  return <div className="rounded-xl bg-[var(--surface-container)] p-6">{children}</div>;
}

function Notice({ tone, children }: { tone: 'error'; children: React.ReactNode }) {
  return (
    <div
      role={tone === 'error' ? 'alert' : undefined}
      className="rounded-lg bg-[var(--surface-container-high)] px-4 py-3 text-label text-[var(--on-surface)]"
    >
      {children}
    </div>
  );
}

function wordCount(text: string): number {
  const trimmed = text.trim();
  return trimmed ? trimmed.split(/\s+/).length : 0;
}

interface RevisionPanelProps {
  revise: NonNullable<DraftingProps['ctx']['revise']>;
  written: number;
  total: number;
  revised: number;
  running: boolean;
  busy: boolean;
  readOnly: boolean;
  onReviseAll: () => void;
  onPause: () => void;
}

/** Revision and Editing: what will be applied, and one button to apply it. */
function RevisionPanel({
  revise,
  written,
  total,
  revised,
  running,
  busy,
  readOnly,
  onReviseAll,
  onPause,
}: RevisionPanelProps) {
  const n = revise.findings.length;
  const from = revise.sources.length ? revise.sources.join(' and ') : 'the stages before this one';
  const unwritten = written < total;

  return (
    <Panel>
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="min-w-0 flex-1">
          <p className="text-label text-[var(--on-surface-variant)]">{revise.stageLabel}</p>
          <p className="mt-1 text-body text-[var(--on-surface)]">
            {revised > 0
              ? `${revised} of ${written} sections revised`
              : n > 0
                ? `${n} accepted finding${n === 1 ? '' : 's'} from ${from} will be applied to each chapter as it stands.`
                : `No accepted findings from ${from}. Each chapter still gets this stage's own pass.`}
          </p>
          {unwritten && (
            <p className="mt-1 text-label text-[var(--on-surface-variant)]">
              {total - written} section{total - written === 1 ? ' is' : 's are'} not written yet — finish
              drafting first, or they will be left out.
            </p>
          )}
          <p className="mt-1 text-label text-[var(--on-surface-variant)]">
            The manuscript as it stands is saved as a version first. Findings you rejected are not applied.
          </p>
        </div>
        {!readOnly && (
          running ? (
            <button
              type="button"
              onClick={onPause}
              disabled={busy}
              className="rounded-lg bg-[var(--surface-container-high)] px-4 py-2 text-label font-semibold text-[var(--on-surface)] disabled:opacity-50"
            >
              Pause
            </button>
          ) : (
            <button
              type="button"
              onClick={onReviseAll}
              disabled={busy || written === 0}
              className="rounded-lg bg-[var(--pm-primary)] px-4 py-2 text-label font-semibold text-[var(--on-primary)] disabled:opacity-50"
            >
              {revised > 0
                ? 'Revise every section again'
                : n > 0
                  ? `Apply ${n} finding${n === 1 ? '' : 's'} to every section`
                  : `Run ${revise.stageLabel.toLowerCase()} on every section`}
            </button>
          )
        )}
      </div>
      {n > 0 && (
        <details className="mt-4">
          <summary className="cursor-pointer text-label font-semibold text-[var(--pm-primary)]">
            Show the findings
          </summary>
          <ul className="mt-2 space-y-1">
            {revise.findings.map((f, i) => (
              <li key={i} className="text-label text-[var(--on-surface)]">
                <span className="text-[var(--on-surface-variant)]">{f.source}:</span> {f.text}
              </li>
            ))}
          </ul>
        </details>
      )}
    </Panel>
  );
}
